### ISSUE TITLE
Doc page headers are not linkable

### ISSUE THREAD

**Issue by kylegc** [appsody/website#255]
**Describe the bug**
I wish to create a URL link to a section of a document, so the user is directed right to the section. For example:
https://appsody.dev/docs/getting-started/installation#upgrading-appsody

However, the headers are not setup properly (with anchors?) to create these links.

**Expected behavior**
I would expect all section headers to be linkable. 

**Actual behaviour**
Headers cannot be linked

**Environment Details (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by skoh7645** [comment]
https://appsody.dev/docs/getting-started/installation#Upgrading-Appsody would work but we should change all urls to be lowercase as you assumed it would be

**Comment by ddunn2** [comment]
This is caused by this code block:
```js
 // Linking between sections on the same document
 const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
 headings.forEach(heading => {
   heading.id = heading.innerText.replace(/ /g, "-");
 });
``` 
Which is [found here](https://github.com/appsody/website/blob/master/src/components/doc.js#L5)
Currently the code just takes each heading in the docs and replaces all the whitespaces with `-` and assigns this value as an ID to the header so we can link to it. 

As @skoh7645 suggested above we could lowercase this and it should work as you'd expect but we could also use something like: 
https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/

Which is a Gatsby plugin that adds GitHub style header links to all of the headers within all of the markdown files. The chainlink icon can also be styled to whatever we wanted it to look like as well. 
This would also mean you could click on each header and it'd give you the URL for it whereas currently you have to decipher that for yourself.

**Comment by ddunn2** [comment]
It'd look like this when you hover: 

<img width="1045" alt="Screenshot 2019-09-17 at 16 02 03" src="https://user-images.githubusercontent.com/25609923/65053874-91590c80-d964-11e9-8fff-37c76c845395.png">

I gave it a shade of Appsody Pink :P

**Comment by neeraj-laad** [comment]
Using these plugins might be a cleaner solution, vs writing this ourselves. 

Are there plugins provided by gatsby or are these separate modules? How well are these maintained / documented / supported?

**Comment by ddunn2** [comment]
The plugin suggested above is an official plugin, maintained and used by Gatsby themselves. 

The documentation is a little sparse, but it's a relatively simple plugin to use (it seems).

**Comment by kylegc** [comment]
Thanks! It works now as I expect!
Note: I did try the URL with uppercase letters before and still wasn't working.
