### ISSUE TITLE
Instructions on adding pull secret is wrong in documentation

### ISSUE THREAD

**Issue by airazabal** [appsody/website#352]
The documentation (https://developer.ibm.com/tutorials/create-appsody-stack/) describes adding a secret as follows:
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: myapp
spec:
  version: 1.0.0
  applicationImage: myapp
  stack: mystack
  service:
    type: NodePort
    port: 8080
  imagePullSecrets:
    - name: mysecret

However, if you look at the CRD, is defined as 
pullSecret: string
so, the addition in the yaml should be:
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: myapp
spec:
  version: 1.0.0
  applicationImage: myapp
  stack: mystack
  service:
    type: NodePort
    port: 8080
  pullSecrets: mysecret

instead.

**Comment by helenmasters** [comment]
@henrynash please could you look into this?

**Comment by henrynash** [comment]
will push new PR today for this

**Comment by henrynash** [comment]
I have already created and merged a PR that corrected the code snippet, but had missed the surrounding text. This PR fixes that as well: https://github.ibm.com/IBMCode/Code-Tutorials/pull/2410

@airazabal Do you agree that the actual attribute should be `pullSecret` not `pullSecrets` (as you initially indicated), since this seems to be what the Appsody Operator supports?

**Comment by airazabal** [comment]
Yes. That'll do it.

**Comment by helenmasters** [comment]
@airazabal the PR has now been merged and the fixes look good to me. Please can you close this issue if you're happy with the changes?

**Comment by airazabal** [comment]
yes please close
